# Generated by Django 4.2.6 on 2023-10-23 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
