# Generated by Django 4.2.6 on 2023-10-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_options_alter_user_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="document",
            field=models.CharField(max_length=100, verbose_name="Numero de cedula"),
        ),
    ]
