# Generated by Django 4.2.6 on 2023-10-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_client_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="enterprise_name",
            field=models.CharField(
                default="Sin registrar",
                max_length=100,
                unique=True,
                verbose_name="Nombre de la empresa",
            ),
        ),
    ]
