# Generated by Django 4.2.6 on 2023-10-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_enterprise_enterprise_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="type",
            field=models.CharField(
                choices=[("1", "Empresa"), ("2", "Técnico")],
                default="1",
                max_length=1,
                verbose_name="Tipo de entidad",
            ),
        ),
    ]
