# Generated by Django 4.2.6 on 2023-11-06 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_enterprise_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnterpiseFollowers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.enterprise",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguidor de empresa",
                "verbose_name_plural": "Seguidores de empresa",
                "db_table": "enterprise_followers",
            },
        ),
    ]
