# Generated by Django 4.2.6 on 2023-11-06 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_enterpisefollowers_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnterpriseViews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views", models.IntegerField(default=0, verbose_name="Visitas")),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.enterprise",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vistas de empresa",
                "verbose_name_plural": "Vistas de empresa",
                "db_table": "enterprise_views",
            },
        ),
    ]
