# Generated by Django 4.2.6 on 2023-11-05 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0008_enterprise_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nombre de la marca"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="checkit/brands",
                        verbose_name="Icono de la marca",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
            ],
            options={
                "verbose_name": "Marca de dispositivo",
                "verbose_name_plural": "Marcas de dispositivos",
                "db_table": "device_brand",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del dispositivo"
                    ),
                ),
                (
                    "serial",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Serial",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Smartphones", "Smartphones"),
                            ("Tablets", "Tablets"),
                            ("Laptops", "Laptops"),
                            ("Desktops", "Desktops"),
                            ("Cámaras", "Cámaras"),
                            ("Reproductores de música", "Reproductores de música"),
                            ("Auriculares", "Auriculares"),
                            ("Altavoces", "Altavoces"),
                            ("Wearables", "Wearables"),
                            (
                                "Electrodomésticos inteligentes",
                                "Electrodomésticos inteligentes",
                            ),
                            ("Consolas de videojuegos", "Consolas de videojuegos"),
                            (
                                "Dispositivos de realidad virtual",
                                "Dispositivos de realidad virtual",
                            ),
                            ("Dispositivos de streaming", "Dispositivos de streaming"),
                            (
                                "Dispositivos de almacenamiento",
                                "Dispositivos de almacenamiento",
                            ),
                            ("Monitores", "Monitores"),
                            ("Impresoras", "Impresoras"),
                            ("Scanners", "Scanners"),
                            ("Teclados", "Teclados"),
                            ("Ratones", "Ratones"),
                            (
                                "Otros dispositivos electrónicos",
                                "Otros dispositivos electrónicos",
                            ),
                        ],
                        default="Smartphones",
                        max_length=200,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Actualizado el",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="checkit/devices",
                        verbose_name="Imagen del dispositivo",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.devicebrand",
                        verbose_name="Marca",
                    ),
                ),
                (
                    "owener",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.client",
                        verbose_name="Dueño",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo",
                "verbose_name_plural": "Dispositivos",
                "db_table": "device",
            },
        ),
    ]
