# Generated by Django 4.2.6 on 2023-11-05 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="owener",
            new_name="owner",
        ),
    ]
