# Generated by Django 4.2.6 on 2023-11-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_rename_owener_device_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="adquisition_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de adquisición"
            ),
        ),
    ]
