# Generated by Django 4.2.6 on 2023-11-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_device_adquisition_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="status",
            field=models.BooleanField(
                default=True, verbose_name="¿El dispositivo está activo?"
            ),
        ),
    ]
