# Generated by Django 4.2.6 on 2023-11-07 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_enterpriseviews"),
        ("dashboard", "0004_device_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo de mantenimiento"
                    ),
                ),
                (
                    "ticket",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Ticket",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha límite"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "Pendiente"),
                            ("2", "En proceso"),
                            ("3", "Finalizado"),
                            ("4", "Cancelado"),
                        ],
                        default="1",
                        max_length=50,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.client",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.device",
                        verbose_name="Dispositivo",
                    ),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.enterprise",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mantenimiento de dispositivo",
                "verbose_name_plural": "Mantenimientos de dispositivos",
                "db_table": "device_maintenance",
            },
        ),
    ]
