# Generated by Django 4.2.6 on 2023-11-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_devicemaintenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicemaintenance",
            name="technician_feedback",
            field=models.TextField(
                blank=True, null=True, verbose_name="Feedback del técnico"
            ),
        ),
    ]
