DEVICE_CATEGORIES = [
    ("Smartphones", "Smartphones"),
    ("Tablets", "Tablets"),
    ("Laptops", "Laptops"),
    ("Desktops", "Desktops"),
    ("Cámaras", "Cámaras"),
    ("Reproductores de música", "Reproductores de música"),
    ("Auriculares", "Auriculares"),
    ("Altavoces", "Altavoces"),
    ("Wearables", "Wearables"),
    ("Electrodomésticos inteligentes", "Electrodomésticos inteligentes"),
    ("Consolas de videojuegos", "Consolas de videojuegos"),
    ("Dispositivos de realidad virtual", "Dispositivos de realidad virtual"),
    ("Dispositivos de streaming", "Dispositivos de streaming"),
    ("Dispositivos de almacenamiento", "Dispositivos de almacenamiento"),
    ("Monitores", "Monitores"),
    ("Impresoras", "Impresoras"),
    ("Scanners", "Scanners"),
    ("Teclados", "Teclados"),
    ("Ratones", "Ratones"),
    ("Otros dispositivos electrónicos", "Otros dispositivos electrónicos"),
]

